module com {
	module netspective {
		module medigy {
			struct EbD_Sensor {
				string deviceDomain;
				string deviceID;
				long timeOfMeasurement;
				float  timeStamp;
			        long pAvgLoad;
			        long iRMS;
			        long vRMS;
			        long zLoad;

			};
			#pragma keylist EbD_Sensor

		};
	};
};

