module com {
	module netspective {
		module medigy {
			struct TempMonitor {
				string deviceDomain;
				string deviceID;
				long timeOfMeasurement;
				short temp;
			};
			#pragma keylist TempMonitor

		};
	};
};
